### PR TITLE
Increase build number to 1 for version 0.5.6.

### PR DESCRIPTION
**Pull request by csadorf**
To trigger rerendering of feedstock in PR.

### CODE REVIEW

**Comment by csadorf** [comment]
@conda-forge-admin, please rerender

**Comment by csadorf** [comment]
@conda-forge-admin, please add noarch: python

**Comment by jakirkham** [comment]
Please create the PR from your fork in the future. Branches on the main feedstock automatically deploy. Have taken the liberty of marking the package deployed by this PR as `broken` given it is a `noarch` package that has a selector and as it was likely not intentional to deploy. Would encourage this PR be closed and the branch deleted.

**Comment by jakirkham** [comment]
Thanks. Sorry for the trouble.

**Comment by csadorf** [comment]
@jakirkham I was just informed by github that I was revoked access to the staged-recipes repository, is that related to this? Should I be concerned?

**Pull request closed without merging**
